package test.projecttojs.actions.generators.reactcomponent;

import com.vp.plugin.model.IAttribute;
import test.projecttojs.actions.ClassDefinition;
import test.projecttojs.actions.generators.Generator;
import test.projecttojs.actions.Helpers;
import test.projecttojs.actions.generators.DefaultSingleGenerator;
import test.projecttojs.actions.generators.reactcomponent.constructor.ConstructorGenerator;
import test.projecttojs.actions.generators.reactcomponent.operations.ExtraOperationsGenerator;
import test.projecttojs.actions.generators.reactcomponent.operations.OperationsGenerator;
import test.projecttojs.actions.generators.reactcomponent.render.RenderGenerator;

import java.util.Arrays;
import java.util.List;

public class ReactComponentGenerator extends DefaultSingleGenerator implements Generator {
    public ReactComponentGenerator(ClassDefinition definition){
        super(definition);
    }

    @Override
    public void generateFullText() {
        ImportsGenerator imports = new ImportsGenerator(this.getDefinition());
        imports.generateFullText();
        String importsCode = imports.getFullText();

        ConstructorGenerator constructor = new ConstructorGenerator(this.getDefinition());
        constructor.generateFullText();
        String constructorCode = constructor.getFullText();

        RenderGenerator render = new RenderGenerator(this.getDefinition());
        render.generateFullText();
        String renderCode = render.getFullText();

        OperationsGenerator operations = new OperationsGenerator(this.getDefinition());
        operations.generateFullText();
        String operationsCode = operations.getFullText();

        ExtraOperationsGenerator extraOperationsGenerator = new ExtraOperationsGenerator(this.getDefinition());
        extraOperationsGenerator.generateFullText();
        String extraOperationsCode = extraOperationsGenerator.getFullText();

        ExportsGenerator exportsGenerator = new ExportsGenerator(this.getDefinition());
        exportsGenerator.generateFullText();
        String exportsCode = exportsGenerator.getFullText();

        this.appendFullText("// " + this.getDefinition().getName() + " React Component\n" +
                "//\n" +
                "// Generated by IC STRATEGY\n" +
                "//\n" +
                "// WARNING: Do not change this code; it will be overwritten by the next generation run!\n" +
                "//          Change the code only in the Visual Paradigm Project.\n\n");
        this.appendFullText(importsCode);
        this.appendFullText("\n" +
                "class " + this.getDefinition().getName() + " extends React.Component {\n" +
                constructorCode +
                "    render() {\n" +
                renderCode + "\n" +
                "    };\n" +
                operationsCode +
                "};\n\n" +
                extraOperationsCode +
                exportsCode);
    }

    public String getFolder() {
        return "react-component";
    }
}
