package test.projecttojs.actions_reflux.generators.store;

import test.projecttojs.actions_reflux.generators.DefaultMultiGenerator;
import test.projecttojs.actions_reflux.generators.MultiGenerator;

public class InitAppGenerator extends DefaultMultiGenerator implements MultiGenerator {
    @Override
    public synchronized void generateFullText() {
        this.appendFullText("require('./store/" + this.getDefinition().getName() + "')().init();\n");
    }

    @Override
    public void generateEndText() {

    }

    @Override
    public void generateBeginText() {
        this.appendFullText("// initApp\n//\n" +
                "// Generated by IC STRATEGY\n" +
                "//\n" +
                "// WARNING: Do not change this code; it will be overwritten with the next generation run!\n" +
                "//          Change the code only in the Visual Paradigm Project.\n//\n" +
                "require('../../js/1-presentation/services/stores/FormStore');\n" +
                "require('../../js/3-domain/stores/ErrorStore');\n");
    }

    public String getFolder() {
        return "";
    }

    public String getName() {
        return "initApp";
    }
}
