package test.projecttojs.actions_reflux.generators;

import test.projecttojs.actions_reflux.ClassDefinition;

public interface Generator extends Runnable {
    /**
     * Returns the full text generated by this <code>Generator</code>
     */
    String getFullText();

    /**
     * Appends text to the end of the full text
     * @param text The text to append
     */
    void appendFullText(String text);

    /**
     * Generates the full text according to a <code>ClassDefinition</code>
     */
    void generateFullText();

    /**
     * Returns the <code>ClassDefinition</code> used in the generator
     */
    ClassDefinition getDefinition();

    /**
     * Returns the folder the file/files should be generated in
     */
    default String getFolder(){
        return null;
    }

    /**
     * Returns the name the of the generated code
     */
    default String getName() {
        return this.getDefinition().getName();
    }

    default void run() {
        this.generateFullText();
    }
}
