package test.projecttojs.actions.generators.action;

import test.projecttojs.actions.generators.DefaultMultiGenerator;
import test.projecttojs.actions.generators.MultiGenerator;

public class ActionInitGenerator extends DefaultMultiGenerator implements MultiGenerator {
    @Override
    public synchronized void generateFullText() {
        this.appendFullText("import { Init as " + this.getDefinition().getName() + "_Init } from './" + this.getDefinition().getName() + "';\n");
    }

    @Override
    public void generateEndText() {
        this.appendFullText("}\n");
    }

    @Override
    public void generateBeginText() {
        this.appendFullText("// Action Init\n//\n" +
                "// Generated by IC STRATEGY\n" +
                "//\n" +
                "// WARNING: Do not change this code; it will be overwritten with the next generation run!\n" +
                "//          Change the code only in Visual Paradigm.\n//\n");
    }

    @Override
    public String getFolder() {
        return "action";
    }

    @Override
    public String getName() {
        return "init";
    }
}
