package test.projecttojs.actions.generators.form;

import test.projecttojs.actions.ClassDefinition;
import test.projecttojs.actions.generators.DefaultSingleGenerator;
import test.projecttojs.actions.generators.Generator;
import test.projecttojs.actions.generators.form.classes.CreateFormGenerator;
import test.projecttojs.actions.generators.form.classes.SelectFormGenerator;
import test.projecttojs.actions.generators.form.classes.UpdateFormGenerator;

public class FormGenerator extends DefaultSingleGenerator implements Generator {
    public FormGenerator(ClassDefinition definition){
        super(definition);
    }

    @Override
    public void generateFullText() {
        ImportsGenerator importsGenerator = new ImportsGenerator(this.getDefinition());
        CreateFormGenerator createFormGenerator = new CreateFormGenerator(this.getDefinition());
        SelectFormGenerator selectFormGenerator = new SelectFormGenerator(this.getDefinition());
        UpdateFormGenerator updateFormGenerator = new UpdateFormGenerator(this.getDefinition());

        importsGenerator.generateFullText();
        createFormGenerator.generateFullText();
        selectFormGenerator.generateFullText();
        updateFormGenerator.generateFullText();

        String importsCode = importsGenerator.getFullText();
        String createFormCode = createFormGenerator.getFullText();
        String updateFormCode = updateFormGenerator.getFullText();
        String selectFormCode = selectFormGenerator.getFullText();

        this.appendFullText("// " + this.getDefinition().getName() + " Forms\n" +
                "// \n" +
                "// Generated by IC STRATEGY\n" +
                "//\n" +
                "// WARNING: Do not change this code; it will be overwritten by the next generation run!\n" +
                "//          Change the code only in the Visual Paradigm Project.\n\n" +
                importsCode +
                "var Entity = new " + this.getDefinition().getName() + "();\n\n" +
                createFormCode + "\n" +
                updateFormCode + "\n" +
                selectFormCode + "\n" +
                "export {\n" +
                "    CreateForm as Create,\n" +
                "    UpdateForm as Update,\n" +
                "    SelectForm as Select\n" +
                "}\n");
    }

    @Override
    public String getFolder() {
        return "form";
    }
}
