package test.projecttojs.actions.generators.form;


import test.projecttojs.actions.generators.DefaultMultiGenerator;
import test.projecttojs.actions.generators.MultiGenerator;

public class FormListGenerator extends DefaultMultiGenerator implements MultiGenerator {
    @Override
    public synchronized void generateFullText() {
        this.appendFullText("import * as " + this.getDefinition().getName() + " from '../form/" + this.getDefinition().getName() + "';\n");
    }

    @Override
    public void generateEndText() {
        this.appendFullText("    }\n" +
                "};");
    }

    @Override
    public void generateBeginText() {
        this.appendFullText("// Form List\n//\n" +
                "// Generated by IC STRATEGY\n" +
                "//\n" +
                "// WARNING: Do not change this code; it will be overwritten with the next generation run!\n" +
                "//          Change the code only in Visual Paradigm.\n//\n");
    }

    @Override
    public String getFolder() {
        return "form";
    }

    @Override
    public String getName() {
        return "FormList";
    }
}
